modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/clayworks/issues"
license = "https://github.com/team-abnormals/clayworks/blob/main/LICENSE.txt"

[[mods]]
    modId = "clayworks"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "clayworks:kiln"
    configBackground = "clayworks:textures/block/terracotta_bricks.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, hatsondogs, five"
    displayURL = "https://www.teamabnormals.com/mods/clayworks"
    displayName = "Clayworks"
    description = '''
    Introduces a new furnace type and several building blocks!
    '''

[[dependencies.clayworks]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.clayworks]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.clayworks]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.2,)"
    ordering = "AFTER"
    side = "BOTH"